-- Create database and use it
-- CREATE DATABASE IF NOT EXISTS timesheet;
-- USE timesheet;

-- Create parent table
CREATE TABLE IF NOT EXISTS timesheet (
    id VARCHAR(20) PRIMARY KEY,
   -- id BIGINT PRIMARY KEY AUTO_INCREMENT,
    date VARCHAR(50) NOT NULL,
    status VARCHAR(50),
    fileName VARCHAR(255),
    fileType VARCHAR(100),
    assignTo VARCHAR(255),
    assignBy VARCHAR(255),
    empName VARCHAR(255),
    empBadgeNo VARCHAR(100),
    empID VARCHAR(100),
    empDept VARCHAR(255),
    inTime VARCHAR(50),
    outTime VARCHAR(50),
    totalInOut VARCHAR(50),
    allDayHrs VARCHAR(50),
    totalHrs VARCHAR(50),
    remarks TEXT,
    otTime VARCHAR(50),
    netMins VARCHAR(50),
    actualWorkHrs VARCHAR(50),
    normalWorkHrs VARCHAR(50),
    fidNo VARCHAR(100),
    companyName VARCHAR(255),
    trade VARCHAR(255),
    tradeCode VARCHAR(100),
    onAM VARCHAR(50),
    offAM VARCHAR(50),
    onPM VARCHAR(50),
    offPM VARCHAR(50),
    ctr VARCHAR(50),
    rec VARCHAR(50),
    avgDailyTD VARCHAR(50),
    highlightDayTG VARCHAR(50),
    aweSDN VARCHAR(50),
    totalNT VARCHAR(50),
    totalOT VARCHAR(50),
    totalNTOT VARCHAR(50),
    fromDate VARCHAR(50),
    untilDate VARCHAR(50),
    location VARCHAR(255),
    mealAllow VARCHAR(50),
    verify VARCHAR(50),
    bpCompany VARCHAR(255),
    earliestEntryTime VARCHAR(50),
    latestEntryTime VARCHAR(50),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (date),
    INDEX (empID),
    INDEX (fidNo),
    INDEX (status),
    INDEX (empName),
    INDEX (location)
) ENGINE=InnoDB;

-- Create child table
CREATE TABLE IF NOT EXISTS timesheetWorkInfo (
	id VARCHAR(20) PRIMARY KEY,
    -- id BIGINT PRIMARY KEY AUTO_INCREMENT,
    timesheetId VARCHAR(20) NOT NULL,
    -- timesheetId BIGINT NOT NULL,
    jobCode VARCHAR(50),
    location VARCHAR(100),
    workingHrs VARCHAR(50),
    overtime VARCHAR(50),
    FOREIGN KEY (timesheetId) REFERENCES timesheet(id) ON DELETE CASCADE
);